### ISSUE TITLE
Change the Hacktoberfest Banner

### ISSUE THREAD

**Issue by Umesh-01** [praveenscience/Hacktoberfest-Project-Ideas#128]
## Description
**I think we should change the banner of Hacktoberfest because new season is commencing soon... 🎊🎉** 

![image](https://user-images.githubusercontent.com/83420185/134724771-54a77797-7e1b-4502-8ae6-dd08622dde82.png)

## Suggestion
**If you also do like to change this then tell me, I will make a PR with one of these image...**

![image](https://user-images.githubusercontent.com/83420185/134724300-95b3b805-8ff3-4b86-8b41-e283f24d0e26.png)
 
**OR**

![image](https://user-images.githubusercontent.com/83420185/134725023-dd58f2e3-6f33-4a9c-876b-f8330fe1bc9d.png)

**Comment by praveenscience** [comment]
Go ahead @Umesh-01, this is awesome. Please change it.
