### ISSUE TITLE
Add a complete project with HTML+CSS+JS?

### ISSUE THREAD

**Issue by ishitaojha** [praveenscience/Hacktoberfest-Project-Ideas#144]
Instead of adding just the project names why don't we add genuine projects which others can use too? 
I have some cool projects and if you allow then I can add them. (Accept and Merge after Oct 1st) :) #142

**Comment by praveenscience** [comment]
Good idea yes...

**Comment by Ashish1323** [comment]
@PranavViswanathan Even I have some projects by myself which I mentioned in #209. Please Let me know so that I can add here a link that can be useful for the community 😇

**Comment by ishitaojha** [comment]
> @praveenscience Even I have some projects by myself which I mentioned in #209. Please Let me know so that I can add here a link that can be useful for the community 😇

Please open a separate PR/Issue and all the best ❤

**Comment by praveenscience** [comment]
@Ashish1323 and @ishitaojha Yes, please both of you proceed. No need to create separate issues! 😁
